### ISSUE TITLE
Great tool!!, Can we add a feature to return to prompt.?

### ISSUE THREAD

**Issue by MMouse23** [thgossler/WebPageHost#2]
Right now the executable keeps the shell frozen that its launched from.
WIth a little effort i can hide it, but it would be nice if not required at all.

**Comment by MMouse23** [comment]
Now i am spawning the exe in a new thread, but in my main script, with a continue to prompt would be great. 
Not urgent / important

**Comment by thgossler** [comment]
Do you mean that the program should have an option to be launched as "fire-and-forget", i.e. not waiting for the executable output but just open the web page and then continue immediately?

**Comment by MMouse23** [comment]
I am using the tool for screen control in complex provisioning prcesses with operators that have no detailed context of whats going in, your tool, shows them the correct state of that process, and status of which ever URL i need them to look at.
Hence i am not using it for scripted scraping but scripted presenting. 
Using scheduled tasks that run interactively i can do that. But its kind of ugly. As the main script thread would wait for the browser to close.

**Comment by thgossler** [comment]
See the latest release.
