### ISSUE TITLE
Great tool!!, Some small bugs / experience feedback

### ISSUE THREAD

**Issue by MMouse23** [thgossler/WebPageHost#3]
1) You write open with Powershell, but that causes the flags to be double "--" instead of single "-" it says user not found if you dont.
2) The help in the current executable does not show all switches, the website image was my only lead.

If you would be able to contact me, or just update the issue, ill see your chat.

Ps, this is for a huge project, i am not reselling, but just opensource.
Let me know how to donate :)

**Comment by thgossler** [comment]
I will check the syntax output for all switches to be included.

Can you explain again, please, your scenario which causes a problem with the dashes in the command line. I didn't get it yet.

**Comment by thgossler** [comment]
@MMouse23, please try to get the syntax help with the following command line. The command you want to get help for needs to be specified.

`webpagehost open --help`

**Comment by MMouse23** [comment]
I found what my issue is.

When I run "dotnet run" the help is exactly like you present in the screenshot.
All the flags and instructions are visible.
In the compiled Exe version (The only one ive seen when creating these tickets.)
The help is stripped down.

Let me get a picture

![image](https://github.com/user-attachments/assets/8c10bd04-0b9d-45b3-a7ae-3ff37dfb7912)


Right, sorry about this ticket, my bad please close it. Everything works, its simply confusing if you dont get the flags right.

**Comment by MMouse23** [comment]
![image](https://github.com/user-attachments/assets/2dc004ef-1dac-4980-8f24-1d40360cc066)

**Comment by MMouse23** [comment]
Perhaps in the basic help, create a pointer to the help section behind "open" but really cosmetics. 
Everything works as designed here.

**Comment by thgossler** [comment]
Thanks for the explanation. I have added a usage example for the open command with the --help argument. This should clarify it.
